general {
    lock_cmd = pidof hyprlock || env WALLPAPER='$WALLPAPER' $HOME/.local/bin/dynamic-hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = "niri msg action load-config-file && systemctl --user restart kanshi.service && niri msg action power-on-monitors"
}

listener {
    timeout = 900
    on-timeout = loginctl suspend
}
